//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int SubeID { get; set; }
        public string subeAdi { get; set; }
        public string subeLokasyon { get; set; }
    }
}
