//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public int carID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string carBrand { get; set; }
        public string carModel { get; set; }
        public string carModelYear { get; set; }
        public string carPacket { get; set; }
        public string Colour { get; set; }
        public Nullable<int> gear { get; set; }
    }
}
