//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int customerNo { get; set; }
        public string customerNameSurname { get; set; }
        public string customerPhone { get; set; }
        public Nullable<int> customerAge { get; set; }
        public Nullable<decimal> customerBalance { get; set; }
        public Nullable<decimal> customerPayment { get; set; }
        public string customerPW { get; set; }
    }
}
