//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rentacar_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int employeeID { get; set; }
        public string employeeNameSurname { get; set; }
        public string employeePhone { get; set; }
        public string employeeTitle { get; set; }
        public string employeeMail { get; set; }
        public Nullable<decimal> empoloyeeWage { get; set; }
        public string empoloyeePw { get; set; }
    }
}
